name: HealthQLApp
options:
  bundleIdPrefix: com.healthql
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

packages:
  HealthQL:
    path: ..

targets:
  HealthQLApp:
    type: application
    platform: iOS
    sources:
      - HealthQLApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.healthql.app
        INFOPLIST_FILE: HealthQLApp/Info.plist
        CODE_SIGN_ENTITLEMENTS: HealthQLApp/HealthQLApp.entitlements
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
    dependencies:
      - package: HealthQL
        product: HealthQL
      - package: HealthQL
        product: HealthQLParser
      - package: HealthQL
        product: HealthQLPlayground
    entitlements:
      path: HealthQLApp/HealthQLApp.entitlements
      properties:
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.access: []
